# Generated by Django 3.1 on 2020-08-25 00:53

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='vaccine',
            new_name='vaccinations',
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='subitter',
            field=models.CharField(default=datetime.datetime(2020, 8, 25, 0, 53, 50, 104101, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
