# Generated by Django 3.1 on 2020-08-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_auto_20200825_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_image',
            field=models.ImageField(default='pet_profile.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='pet',
            name='submitter_image',
            field=models.ImageField(default='profile.png', upload_to=''),
        ),
    ]
