# Generated by Django 3.1 on 2020-08-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0003_auto_20200825_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_image',
            field=models.ImageField(blank=True, default='pet_profile.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='submitter_image',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
