# Generated by Django 3.1 on 2020-08-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0004_auto_20200825_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='submitter_image',
        ),
    ]
