# Generated by Django 3.1 on 2020-08-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0005_remove_pet_submitter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_image',
            field=models.ImageField(blank=True, default='pet_profile.png', null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='subitter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
