# Generated by Django 3.1 on 2020-08-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0006_auto_20200825_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='subitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
