# Generated by Django 3.1 on 2020-08-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0008_auto_20200827_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='subitter',
            new_name='submitter',
        ),
    ]
