# Generated by Django 3.1.2 on 2020-11-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0009_auto_20200827_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pet',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='pet',
            name='submitter',
        ),
        migrations.AddField(
            model_name='pet',
            name='submitter',
            field=models.ManyToManyField(blank=True, default='SPCA', to='adoptions.Submitter'),
        ),
    ]
